---
abstract: ~
author:
  - 'Lee Aylward <lee@laylward.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Discogs
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  URI: 0
  XML::Parser: 0
  perl: 5.8.0
version: 0.02
