---
abstract: 'get music related information and images'
author:
  - 'Lee Aylward <lee@laylward.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Discogs
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  URI: 0
  XML::Simple: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
